[project]
name = "Toborally"
version = "0.1.0"
description = "Play by 'mail' version of Roborally"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
